---
version: '3.8'
volumes:
  sql_data1:
    driver: local
  sql_data2:
    driver: local
  sql_data3:
    driver: local

networks:
  dbnet:
    name: sqlnet
    driver: overlay

services:
  balancer_mysql:
    image: severalnines/proxysql:2.3.2
    hostname: db_balancer   
    networks:
      - dbnet
    ports:
      - 3306:3306
      - 3307:3307
      - 6033:6033 
      - 6032:6032
      - 6080:6080
    configs:
      - source: proxyconf
        target: /etc/proxysql.cnf
    deploy:
      mode: replicated
      replicas: 1
      
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    hostname: phpmyadmin   
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - db1   
    networks:
      - dbnet   
    environment:
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=yes
    deploy:
      mode: replicated
      replicas: 1  
      
  db1:
    image: docker.io/bitnami/mariadb-galera:10.5.17-3
    hostname: db1
    networks:
      - dbnet
    volumes:
      - sql_data1:/bitnami/mariadb
    configs:
      - source: mysqlcnf
        target: /opt/bitnami/mariadb/conf/my_custom.cnf:ro
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=mydbuser
      - MARIADB_PASSWORD=mydbpass
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.node==docker1]
        
  db2:
    image: docker.io/bitnami/mariadb-galera:10.5.17-3
    hostname: db2
    networks:
      - dbnet
    volumes:
      - sql_data2:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=mydbuser
      - MARIADB_PASSWORD=mydbpass
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db1:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=no
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker2]
  db3:
    image: docker.io/bitnami/mariadb-galera:10.5.17-3
    hostname: db3
    networks:
      - dbnet
    volumes:
      - sql_data3:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=mydbuser
      - MARIADB_PASSWORD=mydbpass
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db1:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=no
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker3]

  exporter_mysql_db1:
    image: percona/pmm-client:2
    hostname: pmm_client_db1   
    networks:
      - dbnet
    depends_on:
      - db1
      - pmm_server
    environment:
      - PMM_AGENT_SERVER_ADDRESS=pmm_server:443
      - PMM_AGENT_SERVER_ADDRESS=${PMM_SERVER} 
      - PMM_AGENT_SERVER_USERNAME=root 
      - PMM_AGENT_SERVER_PASSWORD=password 
      - PMM_AGENT_SERVER_INSECURE_TLS=1 
      - PMM_AGENT_SETUP=1 
      - PMM_AGENT_CONFIG_FILE=config/pmm-agent.yaml
     configs:
      - source: pmm_client
        target: config/pmm-agent.yaml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker1]  
   command: pmm-admin add mysql --username=root --password 'password' --host db1  --query-source=perfschema
   
  exporter_mysql_db2:
    image: percona/pmm-client:2
    hostname: pmm_client_db2   
    networks:
      - dbnet
    depends_on:
      - db2
      - pmm_server
    environment:
      - PMM_AGENT_SERVER_ADDRESS=pmm_server:443
      - PMM_AGENT_SERVER_ADDRESS=${PMM_SERVER} 
      - PMM_AGENT_SERVER_USERNAME=root 
      - PMM_AGENT_SERVER_PASSWORD=password 
      - PMM_AGENT_SERVER_INSECURE_TLS=1 
      - PMM_AGENT_SETUP=1 
      - PMM_AGENT_CONFIG_FILE=config/pmm-agent.yaml
    configs:
      - source: pmm_client
        target: config/pmm-agent.yaml      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker2]  
   command: pmm-admin add mysql --username=root --password 'password' --host db2  --query-source=perfschema
   
  exporter_mysql_db3:
    image: percona/pmm-client:2
    hostname: pmm_client_db3 
    networks:
      - dbnet
    depends_on:
      - db3
      - pmm_server
    environment:
      - PMM_AGENT_SERVER_ADDRESS=pmm_server:443
      - PMM_AGENT_SERVER_ADDRESS=${PMM_SERVER} 
      - PMM_AGENT_SERVER_USERNAME=root 
      - PMM_AGENT_SERVER_PASSWORD=password 
      - PMM_AGENT_SERVER_INSECURE_TLS=1 
      - PMM_AGENT_SETUP=1 
      - PMM_AGENT_CONFIG_FILE=config/pmm-agent.yaml
    configs:
      - source: pmm_client
        target: config/pmm-agent.yaml      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker3]  
   command: pmm-admin add mysql --username=root --password 'password' --host db3  --query-source=perfschema   

  exporter_mysql_proxysql:
    image: percona/pmm-client:2
    hostname: pmm_client_proxysql
    networks:
      - dbnet
    depends_on:
      - db_balancer
      - pmm_server
    environment:
      - PMM_AGENT_SERVER_ADDRESS=pmm_server:443
      - PMM_AGENT_SERVER_ADDRESS=${PMM_SERVER} 
      - PMM_AGENT_SERVER_USERNAME=root 
      - PMM_AGENT_SERVER_PASSWORD=password 
      - PMM_AGENT_SERVER_INSECURE_TLS=1 
      - PMM_AGENT_SETUP=1 
      - PMM_AGENT_CONFIG_FILE=config/pmm-agent.yaml
    configs:
      - source: pmm_client
        target: config/pmm-agent.yaml      
    deploy:
      mode: replicated
      replicas: 1
      placement:
   command: pmm-admin add proxysql --username=admin --password=admin --service-name=my-new-proxysql --host=pmm_server --port=6032
   
  pmm_server:
    image: percona/pmm-server:2
    hostname: pmm_server
    networks:
      - dbnet   
    ports:
      - '443:443'
    environment:
      - ENABLE_BACKUP_MANAGEMENT=yes
    deploy:
      mode: replicated
      replicas: 1  

configs:
  pmm_client:
    external: true
    name: pmm-agent.yaml
  proxysql:
    external: true
    name: proxysql.cnf
  mysqlcnf:
    external: true
    name: mysql.cnf
