---
version: '3.8'
volumes:
  sql_data1:
    driver: local
  sql_data2:
    driver: local
  sql_data3:
    driver: local

networks:
  dbnet:
    name: sqlnet
    driver: overlay

services:
  balancer_mysql:
    image: wdmaster/sql_ha:1.0
    hostname: db_balancer   
    networks:
      - dbnet
    ports:
      - 3306:3306
      - 3307:3307
    environment:
      - BACKEND_SERVER_LIST=db1,db2,db3
      - ENABLE_ROOT_USER=1
      - MAX_USER=root
      - MAX_PASS=password
      - REST_USER=admin
      - REST_PASS=password
    deploy:
      mode: replicated
      replicas: 1
      
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    hostname: phpmyadmin   
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - db1   
    networks:
      - dbnet   
    environment:
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=yes
    deploy:
      mode: replicated
      replicas: 1  
      
  db1:
    image: docker.io/bitnami/mariadb-galera:10.5
    hostname: db1
    networks:
      - dbnet
    volumes:
      - sql_data1:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=mydbuser
      - MARIADB_PASSWORD=mydbpass
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.node==docker1]
  db2:
    image: docker.io/bitnami/mariadb-galera:10.5
    hostname: db2
    networks:
      - dbnet
    volumes:
      - sql_data2:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=mydbuser
      - MARIADB_PASSWORD=mydbpass
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db1:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=no
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker2]
  db3:
    image: docker.io/bitnami/mariadb-galera:10.5
    hostname: db3
    networks:
      - dbnet
    volumes:
      - sql_data3:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=mydbuser
      - MARIADB_PASSWORD=mydbpass
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db1:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=no
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker3]

  exporter_mysql_db1:
    image: prom/mysqld-exporter:latest
    hostname: exporter_mysql_db1   
    networks:
      - dbnet
    environment:
      - DATA_SOURCE_NAME="root:password@(db1:3306)/"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker1]  
    command: prom/mysqld-exporter --collect.info_schema.innodb_metrics --collect.info_schema.tablestats --collect.info_schema.tables --collect.info_schema.userstats --collect.engine_innodb_status

  exporter_mysql_db2:
    image: prom/mysqld-exporter:latest
    hostname: exporter_mysql_db2
    networks:
      - dbnet
    environment:
      - DATA_SOURCE_NAME="root:password@(db2:3306)/"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker2]  
    command: prom/mysqld-exporter --collect.info_schema.innodb_metrics --collect.info_schema.tablestats --collect.info_schema.tables --collect.info_schema.userstats --collect.engine_innodb_status
  
      
  exporter_mysql_db3:
    image: prom/mysqld-exporter:latest
    hostname: exporter_mysql_db3
    networks:
      - dbnet
    environment:
      - DATA_SOURCE_NAME="root:password@(db3:3306)/"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:  [node.labels.node==docker3]         
    command: prom/mysqld-exporter --collect.info_schema.innodb_metrics --collect.info_schema.tablestats --collect.info_schema.tables --collect.info_schema.userstats --collect.engine_innodb_status
     
  prometheus:
    image: bitnami/prometheus:latest
    hostname: prometheus
    networks:
      - dbnet   
    ports:
      - '9090:9090'
    deploy:
      mode: replicated
      replicas: 1  
      
